from fastapi import FastAPI, APIRouter, HTTPException
from dotenv import load_dotenv
from starlette.middleware.cors import CORSMiddleware
from motor.motor_asyncio import AsyncIOMotorClient
import os
import logging
from pathlib import Path
from pydantic import BaseModel, Field, ConfigDict
from typing import List, Optional, Dict, Any
import uuid
from datetime import datetime, timezone


ROOT_DIR = Path(__file__).parent
load_dotenv(ROOT_DIR / '.env')

# MongoDB connection
mongo_url = os.environ['MONGO_URL']
client = AsyncIOMotorClient(mongo_url)
db = client[os.environ['DB_NAME']]

app = FastAPI(title="UE5 Quinn Auto-Rigger API")
api_router = APIRouter(prefix="/api")


# ==================== Models ====================

class Vec3(BaseModel):
    x: float = 0.0
    y: float = 0.0
    z: float = 0.0


class Landmark(BaseModel):
    id: str
    label: str
    group: str  # center | left | right | fingers
    placed: bool = False
    position: Vec3 = Field(default_factory=Vec3)
    mirrored: bool = False  # true when auto-generated by symmetry


class SymmetrySettings(BaseModel):
    enabled: bool = True
    axis: str = "x"  # x | y | z


class MeshInfo(BaseModel):
    filename: Optional[str] = None
    format: Optional[str] = None  # glb | gltf | fbx | obj
    vertices: int = 0
    faces: int = 0
    height_m: float = 0.0
    bounds_min: Vec3 = Field(default_factory=Vec3)
    bounds_max: Vec3 = Field(default_factory=Vec3)


class SkeletonTemplateRef(BaseModel):
    name: str = "UE5 Quinn (default)"
    version: str = "1.0"
    bones_count: int = 0
    template_data: Optional[Dict[str, Any]] = None  # store full JSON so a project is self-contained


class Project(BaseModel):
    model_config = ConfigDict(extra="ignore")
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    name: str
    stage: str = "import"  # import | landmarks | skeleton | skinning | validation | export
    mesh: MeshInfo = Field(default_factory=MeshInfo)
    landmarks: List[Landmark] = Field(default_factory=list)
    symmetry: SymmetrySettings = Field(default_factory=SymmetrySettings)
    template: SkeletonTemplateRef = Field(default_factory=SkeletonTemplateRef)
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    updated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class ProjectCreate(BaseModel):
    name: str


class ProjectUpdate(BaseModel):
    name: Optional[str] = None
    stage: Optional[str] = None
    mesh: Optional[MeshInfo] = None
    landmarks: Optional[List[Landmark]] = None
    symmetry: Optional[SymmetrySettings] = None
    template: Optional[SkeletonTemplateRef] = None


class ProjectSummary(BaseModel):
    id: str
    name: str
    stage: str
    landmarks_placed: int
    landmarks_total: int
    updated_at: datetime


# ==================== Helpers ====================

def _serialize(project: Project) -> dict:
    doc = project.model_dump()
    doc['created_at'] = doc['created_at'].isoformat() if isinstance(doc['created_at'], datetime) else doc['created_at']
    doc['updated_at'] = doc['updated_at'].isoformat() if isinstance(doc['updated_at'], datetime) else doc['updated_at']
    return doc


def _deserialize(doc: dict) -> Project:
    doc.pop('_id', None)
    if isinstance(doc.get('created_at'), str):
        doc['created_at'] = datetime.fromisoformat(doc['created_at'])
    if isinstance(doc.get('updated_at'), str):
        doc['updated_at'] = datetime.fromisoformat(doc['updated_at'])
    return Project(**doc)


# ==================== Routes ====================

@api_router.get("/")
async def root():
    return {"message": "UE5 Quinn Auto-Rigger API", "version": "1.0"}


@api_router.get("/health")
async def health():
    return {"status": "ok", "service": "quinn-auto-rigger"}


@api_router.post("/projects", response_model=Project)
async def create_project(payload: ProjectCreate):
    project = Project(name=payload.name)
    await db.projects.insert_one(_serialize(project))
    return project


@api_router.get("/projects", response_model=List[ProjectSummary])
async def list_projects():
    docs = await db.projects.find({}, {"_id": 0}).sort("updated_at", -1).to_list(500)
    summaries = []
    for doc in docs:
        placed = sum(1 for lm in doc.get("landmarks", []) if lm.get("placed"))
        total = len(doc.get("landmarks", [])) or 28
        updated = doc.get("updated_at")
        if isinstance(updated, str):
            updated = datetime.fromisoformat(updated)
        summaries.append(ProjectSummary(
            id=doc["id"],
            name=doc["name"],
            stage=doc.get("stage", "import"),
            landmarks_placed=placed,
            landmarks_total=total,
            updated_at=updated,
        ))
    return summaries


@api_router.get("/projects/{project_id}", response_model=Project)
async def get_project(project_id: str):
    doc = await db.projects.find_one({"id": project_id}, {"_id": 0})
    if not doc:
        raise HTTPException(status_code=404, detail="Project not found")
    return _deserialize(doc)


@api_router.patch("/projects/{project_id}", response_model=Project)
async def update_project(project_id: str, payload: ProjectUpdate):
    doc = await db.projects.find_one({"id": project_id}, {"_id": 0})
    if not doc:
        raise HTTPException(status_code=404, detail="Project not found")
    project = _deserialize(doc)
    update_data = payload.model_dump(exclude_unset=True)
    for k, v in update_data.items():
        setattr(project, k, v)
    project.updated_at = datetime.now(timezone.utc)
    await db.projects.replace_one({"id": project_id}, _serialize(project))
    return project


@api_router.delete("/projects/{project_id}")
async def delete_project(project_id: str):
    result = await db.projects.delete_one({"id": project_id})
    if result.deleted_count == 0:
        raise HTTPException(status_code=404, detail="Project not found")
    return {"ok": True}


# Template validation - checks the uploaded JSON has valid structure
class TemplateValidateRequest(BaseModel):
    template_data: Dict[str, Any]


@api_router.post("/templates/validate")
async def validate_template(payload: TemplateValidateRequest):
    data = payload.template_data
    errors = []
    warnings = []

    if not isinstance(data, dict):
        errors.append("Template root must be an object")
        return {"valid": False, "errors": errors, "warnings": warnings}

    if "bones" not in data or not isinstance(data["bones"], list):
        errors.append("Missing required field: 'bones' (list)")
        return {"valid": False, "errors": errors, "warnings": warnings}

    bones = data["bones"]
    names = set()
    duplicates = []
    for i, b in enumerate(bones):
        if not isinstance(b, dict):
            errors.append(f"Bone {i} is not an object")
            continue
        if "name" not in b:
            errors.append(f"Bone at index {i} is missing 'name'")
            continue
        n = b["name"]
        if n in names:
            duplicates.append(n)
        names.add(n)
        if "parent" not in b:
            warnings.append(f"Bone '{n}' has no 'parent' field (assumed root)")

    if duplicates:
        errors.append(f"Duplicate bone names: {', '.join(sorted(set(duplicates)))}")

    # orphan parent check
    orphans = []
    for b in bones:
        parent = b.get("parent")
        if parent and parent not in names:
            orphans.append(f"{b.get('name')} → {parent}")
    if orphans:
        errors.append(f"Orphan parents: {'; '.join(orphans)}")

    return {
        "valid": len(errors) == 0,
        "errors": errors,
        "warnings": warnings,
        "bones_count": len(bones),
        "name": data.get("name", "Unnamed Template"),
        "version": data.get("version", "1.0"),
    }


app.include_router(api_router)

app.add_middleware(
    CORSMiddleware,
    allow_credentials=True,
    allow_origins=os.environ.get('CORS_ORIGINS', '*').split(','),
    allow_methods=["*"],
    allow_headers=["*"],
)

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)


@app.on_event("shutdown")
async def shutdown_db_client():
    client.close()
